name: Release

on:
  push:
    tags:
      - 'v*'  # Триггерится на теги вида v1.0.0, v1.2.3, etc.
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOOLCHAIN_VERSION: stable-x86_64-pc-windows-msvc
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "README.md LICENSE"
          tag_name: ${{ env.TAG_NAME }}
          name: Shorts Cutter ${{ env.TAG_NAME }}
          body: |
            ## Shorts Cutter ${{ env.TAG_NAME }}
            
            High-performance Rust CLI tool for batch converting horizontal MP4 videos into vertical shorts.
            
            ### Installation
            1. Download the appropriate archive for your platform
            2. Extract the executable
            3. Ensure FFmpeg is installed on your system
            4. Run: `./shorts-cutter --help`
            
            ### Platform Downloads
            - **Linux x64**: `shorts-cutter-linux-x64.zip`
            - **Windows x64**: `shorts-cutter-windows-x64.zip`  
            - **macOS x64**: `shorts-cutter-macos-x64.zip`
            
            ### Usage
            ```bash
            shorts-cutter --input ./videos --output ./shorts --threads 4
            ```
            
            For detailed usage instructions, see the [README](https://github.com/${{ github.repository }}/blob/master/README.md).
          draft: false
          prerelease: false
