name: Release

on:
  push:
    tags:
      - 'v*'  # Триггерится на теги вида v1.0.0, v1.2.3, etc.

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive-suffix: linux-x64
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            archive-suffix: windows-x64
          - target: x86_64-apple-darwin
            os: macos-latest
            archive-suffix: macos-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install ffmpeg

      - name: Rust Release binary
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: release
          ARCHIVE_TYPES: zip
          ARCHIVE_NAME: shorts-cutter-${{ matrix.archive-suffix }}
          TOOLCHAIN_VERSION: stable
          MINIFY: true

  # Дополнительная джоба для создания релиза с описанием
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Shorts Cutter ${{ env.TAG_NAME }}
          body: |
            ## Shorts Cutter ${{ env.TAG_NAME }}
            
            High-performance Rust CLI tool for batch converting horizontal MP4 videos into vertical shorts.
            
            ### Installation
            1. Download the appropriate archive for your platform
            2. Extract the executable
            3. Ensure FFmpeg is installed on your system
            4. Run: `./shorts-cutter --help`
            
            ### Platform Downloads
            - **Linux x64**: `shorts-cutter-linux-x64.zip`
            - **Windows x64**: `shorts-cutter-windows-x64.zip`  
            - **macOS x64**: `shorts-cutter-macos-x64.zip`
            
            ### Usage
            ```bash
            shorts-cutter --input ./videos --output ./shorts --threads 4
            ```
            
            For detailed usage instructions, see the [README](https://github.com/${{ github.repository }}/blob/master/README.md).
          draft: false
          prerelease: false
